django_ensyu2/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'blog'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('article/list/', views.ArticleListView.as_view(), name='article_list'),
    path('article/detail/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('tag/create/', views.TagCreateView.as_view(), name='tag_create'),
    path('tag/list/', views.TagListView.as_view(), name='tag_list'),
    path('article/delete/<int:pk>/', views.ArticleDeleteView.as_view(), name="article_delete"),
    path('article/update/<int:pk>/', views.ArticleUpdateView.as_view(), name="article_update"),
]

django_ensyu2/conf/urls.py
from django.contrib import admin
from django.urls import path, include  # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),  # 追加
]

django_ensyu2/blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')

    # タグは複数紐づく。また、タグを設定しないことも可能にしている(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True, verbose_name='タグ')

    def __str__(self):
        return self.title

django_ensyu2/blog/forms.py
from django import forms
from .models import Tag, Article


class TagCreateForm(forms.ModelForm):

    class Meta:
        model = Tag
        # ページに表示したり、モデルのフィールドを文字列で書きます
        fields = ('name',)


class ArticleCreateForm(forms.ModelForm):

    class Meta:
        model = Article
        # ページに表示したり、モデルのフィールドを文字列で書きます
        fields = ('title', 'text', 'category', 'tags',)


class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'text', 'category', 'tags',)

django_ensyu2/blog/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import TagCreateForm, ArticleCreateForm, ArticleUpdateForm
from .models import Article, Tag



class Home(generic.TemplateView):
    template_name = 'blog/home.html'


class ArticleListView(generic.ListView):
    model = Article
    template_name = 'blog/article_list.html'


class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = 'blog/article_detail.html'


class TagListView(generic.ListView):
    model = Tag  # tag  + _list
    template_name = 'blog/tag_list.html'


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = 'blog/tag_create.html'
    success_url = reverse_lazy('blog:home')
    form_class = TagCreateForm


class ArticleCreateView(generic.CreateView):
    model = Article
    template_name = 'blog/article_create.html'
    success_url = reverse_lazy('blog:home')
    form_class = ArticleCreateForm


class ArticleDeleteView(generic.DeleteView):
    model = Article
    template_name = 'blog/article_delete.html'
    success_url = reverse_lazy('blog:article_list')


class ArticleUpdateView(generic.UpdateView):
    model = Article
    form_class = ArticleUpdateForm
    template_name = 'blog/article_update.html'
    success_url = reverse_lazy('blog:article_list')

django_ensyu2/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

  <a href="{% url 'blog:article_list' %}">記事一覧</a>

  {% block content %} {% endblock %}
</body>
</html>

django_ensyu2/templates/blog/article_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

django_ensyu2/templates/blog/article_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>"{{ object }}"を削除してもよろしいですか?</p>
    <input type="submit" value="削除">
</form>

{% endblock %}

django_ensyu2/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ article.title }}</h1>
    <p>{{ article.text | linebreaks | urlize }}</p>
    <p>{{ article.created_at | date:'Y/m/d H.i.s' }}</p>
    <p>カテゴリ名: {{ article.category.name }} </p>
    <p>タグ:
        {% for tag in article.tags.all %}
            {{ tag.name }},
        {% endfor %}
    </p>
{% endblock %}

django_ensyu2/templates/blog/article_list.html
{%  extends 'base.html' %}


{% block content %}
  {% for article in article_list %}
    <p>
      <a href="{% url 'blog:article_detail' article.id %}">
        {{ article.title }}
      </a>
      /<a href="{% url 'blog:article_update' article.id %}">更新</a>
      /<a href="{% url 'blog:article_delete' article.id %}">削除</a>
<!--      {% for tag in article.tags.all  %} {{ tag.name }} {% endfor %}-->
    </p>
  {% endfor %}
{% endblock %}

django_ensyu2/templates/blog/article_update.html
{% extends 'base.html' %}

{% block content %}
<h2>商品情報更新ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="更新">
</form>

{% endblock %}

django_ensyu2/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
ホームです
{% endblock %}

django_ensyu2/templates/blog/tag_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

django_ensyu2/templates/blog/tag_list.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% for tag in tag_list %}
    <p>{{ tag.name }}</p>
  {% endfor %}
</body>
</html>